import assert from "node:assert/strict";
import { calendarDates, calendarVisible, calendarOrganizationAccess, calendarRequestEvent, selectCalendarPolicy, calendarDayClassification, calendarRowMatches, calendarEmployeeActive, canUseOrganizationCalendar } from "./calendar.utils";

const employee = { _id: "employee", name: "Ashu", code: "SS-461" };
const manager = { _id: "manager", role: "user", permissions: {} };
const hr = { _id: "hr", role: "hr", permissions: { view_leave_requests: true, view_remote_work_requests: true }, hrScope: { departments: ["Engineering"], teams: ["Python"], officeLocations: ["delhi"] } };
const organization = { department: "engineering", departmentNameSnapshot: "Engineering", teamId: "python", teamNameSnapshot: "Python", officeLocation: "delhi", reportingManager: "manager" };
assert.equal(calendarDates("2026-08-31", "2026-09-02").length, 3);
assert.throws(() => calendarDates("2026-02-30", "2026-03-01"));
assert.throws(() => calendarDates("2026-09-02", "2026-09-01"));
assert.throws(() => calendarDates("2026-01-01", "2026-12-31"));
assert.equal(calendarDates("2028-02-28", "2028-03-01").length, 3);
assert.equal(calendarVisible(manager, "reportees", employee, organization), true);
assert.equal(calendarVisible(manager, "reportees", employee, { ...organization, reportingManager: "amit" }), false);
assert.equal(calendarVisible(manager, "mine", employee, organization), false);
assert.equal(calendarVisible(hr, "organization", employee, organization), true);
assert.equal(calendarOrganizationAccess(hr, { ...organization, officeLocation: "mumbai" }), false);
assert.equal(calendarOrganizationAccess(hr, { ...organization, teamNameSnapshot: "Fullstack" }), false);
assert.equal(calendarOrganizationAccess(hr, null), false);
assert.equal(calendarVisible(hr, "organization", employee, organization, { departmentId: "sales" }), false);
assert.equal(canUseOrganizationCalendar(manager), false);
assert.equal(canUseOrganizationCalendar(hr), true);

const assignment = (scopeType: string, resource: string, effectiveFrom = "2026-01-01", effectiveTo: string | null = null) => ({ scopeType, resource, effectiveFrom, effectiveTo });
const version = (schedule: string, versionNumber: number, effectiveFrom: string, status = "published") => ({ _id: `${schedule}-v${versionNumber}`, schedule, versionNumber, effectiveFrom, status });
const assignments = [assignment("company", "default"), assignment("location", "delhi", "2026-08-01", "2026-09-01")];
const versions = [version("default", 1, "2026-01-01"), version("default", 2, "2026-09-01"), version("delhi", 1, "2026-08-01"), version("delhi", 2, "2026-08-15", "draft")];
assert.equal(selectCalendarPolicy(assignments, versions, "2026-07-31")?.version._id, "default-v1");
assert.equal(selectCalendarPolicy(assignments, versions, "2026-08-31")?.version._id, "delhi-v1");
assert.equal(selectCalendarPolicy(assignments, versions, "2026-09-01")?.version._id, "default-v2");
assert.equal(selectCalendarPolicy([assignment("company", "missing")], versions, "2026-09-01"), null);
const schedule = { version: { rules: { workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], saturdayRule: "second_and_fourth_off", startTime: "19:00", endTime: "02:00", timezone: "Asia/Kolkata" } } };
assert.equal(calendarDayClassification("2026-09-12", schedule, null).dayType, "weekly_off");
assert.equal(calendarDayClassification("2026-09-05", schedule, null).dayType, "working_day");
assert.equal(calendarDayClassification("2026-09-07", schedule, { version: { holidays: [{ date: "2026-09-07", name: "Festival", type: "mandatory" }] } }).dayType, "mandatory_holiday");
assert.equal(calendarDayClassification("2026-09-07", schedule, { version: { holidays: [{ date: "2026-09-07", name: "Optional festival", type: "optional" }] } }).requiresAttendance, true);
assert.equal(calendarDayClassification("2026-09-07", schedule, null).schedule.grossMinutes, 420);
assert.equal(calendarEmployeeActive({ joiningDate: "2026-09-10", employmentEndDate: "2026-10-10" }, "2026-09-01"), false);
assert.equal(calendarEmployeeActive({ joiningDate: "2026-09-10", employmentEndDate: "2026-10-10" }, "2026-10-11"), false);

const request = { _id: "request", employee: "employee", leaveTypeNameSnapshot: "Sick Leave", leaveTypeCodeSnapshot: "SL", leaveUnit: "days", fromDate: "2026-09-14", toDate: "2026-09-14", reason: "Private medical reason", status: "submitted", currentApprovers: ["manager"], approvalInstance: "workflow" };
const day = { attendanceDate: "2026-09-14", portion: "first_half", chargedUnits: 0.5, units: 0.5 };
const event = calendarRequestEvent(manager, "reportees", employee, organization, "leave", request, day)!;
assert.equal(event.canApprove, true);
assert.equal(event.portion, "first_half");
assert.equal(event.units, 0.5);
assert.equal(event.reason, request.reason);
assert.equal(calendarRequestEvent({ ...manager, _id: "other" }, "reportees", employee, organization, "leave", request, day), null);
assert.equal(calendarRequestEvent(manager, "reportees", employee, organization, "leave", { ...request, currentApprovers: [] }, day), null);
const self = calendarRequestEvent({ _id: "employee", role: "user" }, "mine", employee, organization, "leave", request, day)!;
assert.equal(self.canApprove, false);
assert.equal(self.canWithdraw, true);
assert.equal(calendarRequestEvent(manager, "reportees", employee, organization, "leave", { ...request, status: "cancelled" }, day), null);
assert.equal(calendarRequestEvent(manager, "reportees", employee, organization, "leave", { ...request, status: "approved" }, { ...day, chargedUnits: 0 }), null);
const redacted = calendarRequestEvent({ _id: "peer", role: "user" }, "reportees", employee, { ...organization, reportingManager: "manager" }, "leave", { ...request, status: "approved" }, day)!;
assert.equal(redacted.title, "On leave");
assert.equal(redacted.reason, "");
assert.equal(calendarRowMatches({ events: [event], dayType: "working_day", holiday: null }, "leave", false), false);
assert.equal(calendarRowMatches({ events: [event], dayType: "working_day", holiday: null }, "leave", true), true);
assert.equal(calendarRowMatches({ events: [{ ...event, kind: "wfh", status: "approved" }], dayType: "working_day", holiday: null }, "leave", true), false);
console.log("Calendar tests passed (41 assertions)");
